Address = tuple[str, int]

PROTO_MAGIC = b"\x42\x6D\x0A"
HEADER_SIZE = 8
MAC_SIZE = 8
MAX_FRAME_SIZE = 10 * 1024 * 1024

DEFAULT_PORT = 10000
DEFAULT_CONNECT_TIMEOUT = 5.0
DEFAULT_REQUEST_TIMEOUT = 10.0
DEFAULT_IDLE_TIMEOUT = 3.0
DEFAULT_RECONNECT_DELAY = 5.0
EXTENSION_VERSION = 11

LOGIN_FLAG_SPREADING_TRANSACTIONS = 0x01
LOGIN_FLAG_SEND_PEERS = 0x04

MSG_BYE = 0x01
MSG_PING = 0x02
MSG_PONG = 0x03
MSG_SCHANNEL_INIT = 0x04
MSG_SCHANNEL_READY = 0x05
MSG_AUTHENTICATION = 0x06
MSG_PEER_INFO = 0x08
MSG_GET_TIME = 0x0B
MSG_TIME = 0x0C
MSG_LOGIN = 0x0F
MSG_NEW_TIP = 0x10
MSG_HAVE_TRANSACTION = 0x31
MSG_GET_TRANSACTION = 0x32
MSG_STATUS = 0x44
MSG_NEW_TRANSACTION = 0x49

MSG_NAMES = {
    MSG_BYE: "Bye",
    MSG_PING: "Ping",
    MSG_PONG: "Pong",
    MSG_SCHANNEL_INIT: "SChannelInitiate",
    MSG_SCHANNEL_READY: "SChannelReady",
    MSG_AUTHENTICATION: "Authentication",
    MSG_PEER_INFO: "PeerInfo",
    MSG_GET_TIME: "GetTime",
    MSG_TIME: "Time",
    MSG_LOGIN: "Login",
    MSG_NEW_TIP: "NewTip",
    MSG_HAVE_TRANSACTION: "HaveTransaction",
    MSG_GET_TRANSACTION: "GetTransaction",
    MSG_STATUS: "Status",
    MSG_NEW_TRANSACTION: "NewTransaction",
}